### PR TITLE
New version

### PR DESCRIPTION
**Pull request by danse**
Changed the version number. `grunt bump` created a tag in my local fork so i will push the tag to upstream once you will merge this, as a way to have an acknowledgement from you

### CODE REVIEW

**Comment by tthew** [comment]
@danse hmmm, I think this is probably more than just a patch bump.  Would be more comfortable with a minor or even major breaking change bump....

**Comment by danse** [comment]
which part of the interface changed? how should users update when switching to the new version? i see that most of the tests are still intact. maybe what changed was [zero indexing for months](https://github.com/eHealthAfrica/angular-eha.date-of-birth-or-age/pull/6/files#diff-826c7b31f0d56ec2884ae8c414f9fd82R51)? other dates changed in the tests so i am not sure. or maybe you refer to removing the `form`?

**Comment by tthew** [comment]
Well the previous version didn't work properly. I guess it just slipped through unnoticed. As I mostly just copied pasted from legacy, wrote some basic tests and did some very basic user testing, but I guess I only tested the happy path.  This version actually works as it should. 

So perhaps rather than a 'breaking change' it's a 'fixing change' :P - either way certainly feels like more than just a patch.  But I'm really not going to hold you back from merging based on my 'feelings'. Already spent way more time on this that I ever anticipated. So go, merge, merge away! :)

**Comment by danse** [comment]
all right :)

**Pull request merged**
