### PR TITLE
Refactor / Fix issues.

### LINKED ISSUE #4: Age or Date directive always sets the current month
See https://github.com/eHealthAfrica/lr-ebola-cases/issues/392

### LINKED ISSUE #5: Directive contains its own form-tag
https://github.com/eHealthAfrica/angular-eha.date-of-birth-or-age/blob/master/src/date-of-birth-or-age.directive.tpl.html#L2

### PR DESCRIPTION
**Pull request by tthew**
Fixes #4
Fixes #5

[Demo (JS Bin)](http://jsbin.com/tesutiwude/1/edit?html,js,output)

@karlwestin @danse

### CODE REVIEW

**Comment by espy** [comment]
Wheeeeee :D

**Comment by danse** [comment]
:+1: thanks Matt!

**Comment by danse** [comment]
hum once your are there, would you update the change log?

**Comment by tthew** [comment]
@danse done (but to be honest, it doesn't really add anything!)

**Comment by danse** [comment]
Hum there are two bugs fixed. Okay merging now. Will you do the new release or can i do it?

**Comment by tthew** [comment]
@danse ah yeah I suppose. I approached it more as a refactor as most of the original implementation was just copied / pasted from sense followup.

**Pull request merged**
